version: '3'
services:
  vokke.test:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: vokke-1.0/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '9000:9000'
      - '3000:3000'
    environment:
      WWWUSER: '${WWWUSER}'
      XDEBUG_MODE: '${VOKKE_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${VOKKE_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/html'
    networks:
      - vokke
    depends_on:
      - mysql
      - redis
  mysql:
    image: 'mysql/mysql-server:5.7'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'vokke-mysql:/var/_lib/mysql'
    networks:
      - vokke
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'vokke-redis:/data'
    networks:
      - vokke
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
networks:
  vokke:
    driver: bridge
volumes:
  vokke-mysql:
    driver: local
  vokke-redis:
    driver: local
